# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'pkimport' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pkimport
  pod 'Kingfisher', '~> 4.6'

  target 'pkimportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pkimportUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
